version: "3.9"

services:

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ${REDIS_CACHE_DIR:-./data/cache}:/data

  db:
    image: postgres:latest
    volumes:
      - ${PG_DATA_DIR:-./data/db}:/var/lib/postrgresql/data/
    ports:
      - ${PG_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DB:-litestar-test}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U postgres"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
